name: dabble_server
version: 0.0.1
description: Dabble's server
dependencies:
  browser: any
  lawndart: any
  pathos: any
  serialization: any
  stream: any
  web_ui: any

#dependencies:
#  js: any
#  unittest: any