//Auto-generated by RSP Compiler
//Source: server/web/live.rsp.html
part of dabble.server;

/** Template, live, for rendering the view. */
void live(HttpConnect connect) { //6
  var _cs_ = new List<HttpConnect>(), request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");
String id = connect.dataset['id'];
  ADabble dabble = getDabble(id);

  response.write("""

<!DOCTYPE html>
<html>
  <head>
    <title>"""); //#6

  response.write(nnstr(dabble.current.name)); //#10


  response.write("""
</title>
    <link href="theme.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <h1 id='name'>"""); //#10

  response.write(nnstr(dabble.current.name)); //#14


  response.write("""
</h1>
    <iframe id="render-area"></iframe>
<script src="/packages/browser/dart.js"></script>
<script type="application/dart" src="/live.dart"></script>
</body></html>
"""); //#14

  connect.close();
}
